name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      run: |
        curl -L -o python.tar.gz https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz
        tar xf python.tar.gz
        cd Python-3.10.0
        ./configure --enable-optimizations
        make altinstall

    - name: Install PyInstaller
      run: python3.10 -m pip install pyinstaller

    - name: Build exe
      run: pyinstaller --onefile your_script.py

    - name: Upload exe
      uses: actions/upload-artifact@v2
      with:
        name: exe
        path: ./dist
