name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 将仓库内容检出到工作目录

    - name: List files and directories in workspace
      run: ls -al /github/workspace  # 列出工作目录的内容
