name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.x64 

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build exe
      run: pyinstaller --onefile main.py 

    - name: Upload exe
      uses: actions/upload-artifact@v2
      with:
        name: exe
        path: ./dist

